version: '3.8'
services:
  # Base PostgreSQL pour school-service
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: schooldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Base MongoDB pour student-service
  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Service de découverte Consul
  consul:
    image: consul:1.15.3
    container_name: consul_service
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"       # Interface web de Consul
      - "8600:8600/udp"   # Résolution DNS pour les services
    environment:
      CONSUL_BIND_INTERFACE: eth0
    volumes:
      - consul_data:/consul/data

  # Microservice school-service (Node + Express)
  school-service:
    build:
      context: ./school-service
      dockerfile: Dockerfile
    container_name: school_service
    ports:
      - "8081:8081"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: schooldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      CONSUL_HTTP_ADDR: "http://consul_service:8500"
    depends_on:
      - postgres
      - consul
    volumes:
      - ./school-service:/app
      - /app/node_modules

  # Microservice student-service (Node + Express + Mongoose)
  student-service:
    build:
      context: ./student-service
      dockerfile: Dockerfile
    container_name: student_service
    ports:
      - "8082:8082"
    environment:
      MONGO_URI: "mongodb://mongo_db:27017/studentdb"
      SCHOOL_SERVICE_URL: "http://school_service:8081"
      CONSUL_HTTP_ADDR: "http://consul_service:8500"
    depends_on:
      - mongo
      - school-service
      - consul
    volumes:
      - ./student-service:/app
      - /app/node_modules

  # Front Vue (Vite + Express)
  vue-front:
    build:
      context: ./my-vue-front
      dockerfile: Dockerfile
    container_name: vue_front
    ports:
      - "8080:8080"
    environment:
      CONSUL_HTTP_ADDR: "http://consul_service:8500"
    depends_on:
      - consul
      - school-service
      - student-service

volumes:
  postgres_data:
  mongo_data:
  consul_data:
